services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    container_name: anidex
    depends_on:
      - redis
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - REDIS_URL=redis://redis:6379
    # develop:
    #   watch:
    #     - action: sync
    #       path: .
    #       target: /app
    #       ignore:
    #         - node_modules
    #         - .next
  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"